### ISSUE TITLE
Why remove empty result query samples

### ISSUE THREAD

**Issue by Eilowangfang** [andreaskipf/learnedcardinalities#2]
Hi, in the paper, you mentioned that during generating random query samples as training data, 
the queries with empty results are kipped. 
May I asked the motivation that we remove the empty-result query?
Is that such queries are meaningless in real word from user view (which I might not agree)
Or, the MSCN model cannot general well with such empty-result queries?

**Comment by andreaskipf** [comment]
Hi, that is a fair question. Our training data generation process, as described in the paper, produces many empty-result queries. Actually most of the queries are empty. The reason is that we try random predicate and join combinations. I presume that with a more intelligent generation process you could avoid that situation in many cases (it would also be more efficient).

We skipped them for simplicity. I don't think the model would have issues with empty-result queries. As a first step, you could try adding something like 10% empty-result queries to the mix (to the training and the test data). I'd be curious about the results!
